/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package detodosa;


import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author juan_
 */
public class BusquedaPorNombreView extends javax.swing.JInternalFrame {
    
    
    
    
    private DefaultTableModel modelo = new DefaultTableModel(){
        
        public boolean isCelleEditable(int f, int c){
            return false;
    }

};
    private TableRowSorter trs;

   
    /**
     * Creates new form BusquedaPorNombreView
     */
    public BusquedaPorNombreView() {
        initComponents();
        armarCabecera();
         for(Producto prod : ventanaGeneral.listaProductos){
                modelo.addRow(new Object[]{
                prod.getCodigo(),
                prod.getDescripcion(),
                prod.getPrecio(),                  
                prod.getStock()
                });
        }
         
        int x = (int) (280/2);
        int y = (int) (100 / 2);
        this.setLocation(x, y);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNombreABuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setText("Listado por Nombre");

        jLabel2.setText("Escriba los primeros caracteres");

        jtNombreABuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNombreABuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtNombreABuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNombreABuscarKeyTyped(evt);
            }
        });

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtNombreABuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNombreABuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNombreABuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreABuscarKeyReleased
        // TODO add your handling code here:
        borrarFilas();
        String texto = jtNombreABuscar.getText().toLowerCase();
        
        for(Producto prod : ventanaGeneral.listaProductos){
            if (prod.getDescripcion().toLowerCase().startsWith(texto)) {
                modelo.addRow(new Object[]{
                prod.getCodigo(),
                prod.getDescripcion(),
                prod.getPrecio(),                  
                prod.getStock()
                });
            }
        }
    }//GEN-LAST:event_jtNombreABuscarKeyReleased

    private void jtNombreABuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreABuscarKeyTyped
        // TODO add your handling code here:
        //Código para filtrar la tabla.
//        jtNombreABuscar.addKeyListener(new KeyAdapter() {
//        @Override
//        public void keyReleased(KeyEvent e) {
//            trs.setRowFilter(RowFilter.regexFilter("(?i)"+jtNombreABuscar.getText(), 1));
////            System.out.println("asdasd");
//        }
//        });
//
//        modelo= (DefaultTableModel) jtProductos.getModel();
//        trs = new TableRowSorter(modelo);
//        jtProductos.setRowSorter(trs);   
        
    }//GEN-LAST:event_jtNombreABuscarKeyTyped

    private void jtNombreABuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreABuscarKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtNombreABuscarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtNombreABuscar;
    private javax.swing.JTable jtProductos;
    // End of variables declaration//GEN-END:variables
   
    private void armarCabecera(){
    modelo.addColumn("Código");
    modelo.addColumn("Descripción");
    modelo.addColumn("Precio");
    modelo.addColumn("Stock");
    jtProductos.setModel(modelo);
    }

    private void borrarFilas(){
        int filas = jtProductos.getRowCount()-1;
        for(int f = filas;f>=0; f--){
            
            modelo.removeRow(f);
        }
        
    }
}
